"""add payment fields and book pricing

Revision ID: 6b5cb45ffefd
Revises: 39978fb9436c
Create Date: 2026-08-24 20:10:18.439457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5cb45ffefd'
down_revision: Union[str, None] = '39978fb9436c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status', existing_type=sa.String(length=20), type_=sa.String(length=50), existing_nullable=True)
    op.add_column('books', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('item_type', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('book_id', sa.String(length=36), nullable=True))
    op.add_column('payments', sa.Column('plan_id', sa.String(length=36), nullable=True))
    op.add_column('payments', sa.Column('gateway_reference', sa.String(length=128), nullable=True))
    op.add_column('payments', sa.Column('payment_metadata', sa.JSON(), nullable=True))
    op.add_column('payments', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_payments_plan_id', 'payments', 'subscription_plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_payments_book_id', 'payments', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status', existing_type=sa.String(length=50), type_=sa.String(length=20), existing_nullable=True)
    op.drop_constraint('fk_payments_plan_id', 'payments', type_='foreignkey')
    op.drop_constraint('fk_payments_book_id', 'payments', type_='foreignkey')
    op.drop_column('payments', 'completed_at')
    op.drop_column('payments', 'payment_metadata')
    op.drop_column('payments', 'gateway_reference')
    op.drop_column('payments', 'plan_id')
    op.drop_column('payments', 'book_id')
    op.drop_column('payments', 'item_type')
    op.drop_column('books', 'price')
    # ### end Alembic commands ###
