"""add verification codes table

Revision ID: 77a24989ebc9
Revises: bba47b860ddb
Create Date: 2026-09-24 13:30:23.846991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a24989ebc9'
down_revision: Union[str, None] = 'bba47b860ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_codes_channel_target', 'verification_codes', ['channel', 'target'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_codes_channel_target', table_name='verification_codes')
    op.drop_table('verification_codes')
    # ### end Alembic commands ###
