"""add store metadata, indexes and integrity constraints

Revision ID: bba47b860ddb
Revises: 8a2f1c4e9b7d
Create Date: 2026-09-23 18:25:21.472566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba47b860ddb'
down_revision: Union[str, None] = '8a2f1c4e9b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_categories_book_id'), 'book_categories', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_categories_category_id'), 'book_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_book_media_book_id'), 'book_media', ['book_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_book_id'), 'bookmarks', ['book_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_chapter_id'), 'bookmarks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_client_id'), 'bookmarks', ['client_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.add_column('books', sa.Column('publisher', sa.String(length=255), nullable=True))
    op.add_column('books', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('sales_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chapters_book_id'), 'chapters', ['book_id'], unique=False)
    op.create_index(op.f('ix_collection_books_book_id'), 'collection_books', ['book_id'], unique=False)
    op.create_index(op.f('ix_collection_books_collection_id'), 'collection_books', ['collection_id'], unique=False)
    op.create_unique_constraint('uq_collection_book', 'collection_books', ['collection_id', 'book_id'])
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_index(op.f('ix_notes_book_id'), 'notes', ['book_id'], unique=False)
    op.create_index(op.f('ix_notes_chapter_id'), 'notes', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_notes_client_id'), 'notes', ['client_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_reading_progress_book_id'), 'reading_progress', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_progress_user_id'), 'reading_progress', ['user_id'], unique=False)
    op.create_unique_constraint('uq_reading_progress_user_book', 'reading_progress', ['user_id', 'book_id'])
    op.create_index(op.f('ix_reading_sessions_book_id'), 'reading_sessions', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_sessions_user_id'), 'reading_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_checkpoints_device_id'), 'sync_checkpoints', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_checkpoints_user_id'), 'sync_checkpoints', ['user_id'], unique=False)
    op.create_unique_constraint('uq_sync_checkpoint_user_device', 'sync_checkpoints', ['user_id', 'device_id'])
    op.create_index(op.f('ix_sync_conflicts_user_id'), 'sync_conflicts', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_queue_device_id'), 'sync_queue', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_queue_user_id'), 'sync_queue', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_books_book_id'), 'user_books', ['book_id'], unique=False)
    op.create_index(op.f('ix_user_books_user_id'), 'user_books', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_book', 'user_books', ['user_id', 'book_id'])
    op.create_index(op.f('ix_user_subscriptions_plan_id'), 'user_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_plan_id'), table_name='user_subscriptions')
    op.drop_constraint('uq_user_book', 'user_books', type_='unique')
    op.drop_index(op.f('ix_user_books_user_id'), table_name='user_books')
    op.drop_index(op.f('ix_user_books_book_id'), table_name='user_books')
    op.drop_index(op.f('ix_sync_queue_user_id'), table_name='sync_queue')
    op.drop_index(op.f('ix_sync_queue_device_id'), table_name='sync_queue')
    op.drop_index(op.f('ix_sync_conflicts_user_id'), table_name='sync_conflicts')
    op.drop_constraint('uq_sync_checkpoint_user_device', 'sync_checkpoints', type_='unique')
    op.drop_index(op.f('ix_sync_checkpoints_user_id'), table_name='sync_checkpoints')
    op.drop_index(op.f('ix_sync_checkpoints_device_id'), table_name='sync_checkpoints')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_reading_sessions_user_id'), table_name='reading_sessions')
    op.drop_index(op.f('ix_reading_sessions_book_id'), table_name='reading_sessions')
    op.drop_constraint('uq_reading_progress_user_book', 'reading_progress', type_='unique')
    op.drop_index(op.f('ix_reading_progress_user_id'), table_name='reading_progress')
    op.drop_index(op.f('ix_reading_progress_book_id'), table_name='reading_progress')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_client_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_chapter_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_book_id'), table_name='notes')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_constraint('uq_collection_book', 'collection_books', type_='unique')
    op.drop_index(op.f('ix_collection_books_collection_id'), table_name='collection_books')
    op.drop_index(op.f('ix_collection_books_book_id'), table_name='collection_books')
    op.drop_index(op.f('ix_chapters_book_id'), table_name='chapters')
    op.drop_column('books', 'sales_count')
    op.drop_column('books', 'rating_count')
    op.drop_column('books', 'rating')
    op.drop_column('books', 'publisher')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_client_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_chapter_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_book_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_book_media_book_id'), table_name='book_media')
    op.drop_index(op.f('ix_book_categories_category_id'), table_name='book_categories')
    op.drop_index(op.f('ix_book_categories_book_id'), table_name='book_categories')
    # ### end Alembic commands ###
