"""
CSRF token generation and validation for admin portal.

Stateless, HMAC-signed tokens (session_id + timestamp + signature) - no
server-side storage needed, so verification works correctly regardless of
how many uvicorn worker processes are running or whether Redis is
available. A token generated by one worker is verifiable by any other
worker, since validity only depends on the shared SECRET_KEY.
"""

import base64
import hmac
import hashlib
import time
import logging

from app.core.config import settings

logger = logging.getLogger(__name__)

CSRF_TOKEN_EXPIRY_SECONDS = 86400  # 24 hours


def _sign(session_id: str, timestamp: str) -> str:
    message = f"{session_id}:{timestamp}".encode()
    return hmac.new(settings.SECRET_KEY.encode(), message, hashlib.sha256).hexdigest()


async def generate_csrf_token(session_id: str) -> str:
    """Generate a signed CSRF token for a session. No storage required."""
    timestamp = str(int(time.time()))
    signature = _sign(session_id, timestamp)
    raw = f"{timestamp}:{signature}"
    return base64.urlsafe_b64encode(raw.encode()).decode()


async def verify_csrf_token(session_id: str, token: str) -> bool:
    """Verify a signed CSRF token for a session using constant-time comparison."""
    if not token or not session_id:
        return False
    try:
        raw = base64.urlsafe_b64decode(token.encode()).decode()
        timestamp, signature = raw.split(":", 1)
    except (ValueError, UnicodeDecodeError):
        return False

    if time.time() - int(timestamp) > CSRF_TOKEN_EXPIRY_SECONDS:
        return False

    expected = _sign(session_id, timestamp)
    return hmac.compare_digest(expected, signature)


async def revoke_csrf_tokens(session_id: str) -> None:
    """No-op: tokens are stateless and expire on their own (24h)."""
    return None
